# rm(list=ls())

## ---- libraries ----
library(data.table)
library(ggeffects)
library(ggplot2)
library(ggpubr)
library(performance)
library(scales)
library(dplyr)
library(tidyr)
library(ggh4x)
library(stats)
library(pscl)
library(broman)
library(survminer)
library(broom.helpers)
library(broom.mixed)
library(emmeans)
library(cowplot)
library(survival)
library(ggsurvfit)
library(survminer)
library(forcats)
library(sjPlot)
library(rstatix)
library(ggprism)
library(MASS)
library(flextable)
library(officer)
library(kableExtra)
library(knitr)
library(officedown)
library(DataCombine)
library(car)



# plot